[platformio]
default_envs = cyd

[env:cyd]
platform = espressif32@6.9.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.partitions = default.csv

lib_deps =
  bodmer/TFT_eSPI@^2.5.33
  tzapu/WiFiManager@^2.0.17
  bblanchon/ArduinoJson@^7.2.1
  https://github.com/PaulStoffregen/XPT2046_Touchscreen.git

build_flags =
  -DUSER_SETUP_LOADED
  -DUSE_HSPI_PORT
  -DTFT_MISO=12
  -DTFT_MOSI=13
  -DTFT_SCLK=14
  -DTFT_CS=15
  -DTFT_DC=2
  -DTFT_RST=-1
  -DSPI_FREQUENCY=55000000
  -DSPI_READ_FREQUENCY=20000000
  -DLOAD_GLCD
  -DLOAD_FONT2
  -DLOAD_FONT4
  -DLOAD_GFXFF
  -DILI9341_2_DRIVER
  -DTFT_RGB_ORDER=TFT_BGR
  -DTFT_INVERSION_ON
